name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Bundle the web app
      uses: swiftwasm/swiftwasm-action@v5.6
      with:
        shell-action: carton bundle
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./Bundle
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
